#!/bin/bash

# Exit on error
set -e

# --- Configuration ---
PROJECT_ID_BASE="ge-flip-$(date +%s)"
REGION="us-central1"
REPOSITORY_NAME="ge-analyzer-repo"
IMAGE_NAME="ge-analyzer-server"
SERVICE_NAME="ge-analyzer-service"
CONTAINER_PORT="8080"
CPU="4"
MEMORY="4Gi"

# !! HARDCODED IDENTITIES FOR ACCESS CONTROL !!
CORP_EMAIL="lucasmolander@google.com"
PERSONAL_EMAIL="lucas.mark.molander@gmail.com"

echo "================================================================="
echo "   OSRS GE Flip Analyzer - GCP Playground Deployment Bootstrapper"
echo "================================================================="
echo "Corporate Access:  ${CORP_EMAIL}"
echo "Personal Access:   ${PERSONAL_EMAIL}"
echo "Region:            ${REGION}"
echo "================================================================="
echo ""

# --- 1. Create GCP Playground Project ---
echo "Step 1: Creating GCP Playground project..."
# Use cloudwerkcli to create a playground project.
# This command appends a random suffix to ensure uniqueness.
# We capture stderr and stdout to a temporary file to provide robust debugging.
TMP_OUTPUT=$(mktemp)
trap 'rm -f "$TMP_OUTPUT"' EXIT

set +e
/google/bin/releases/chp-hia-team/cloudwerkcli/cloudwerkcli \
  --use_case="playground" \
  --add_random_suffix=true \
  --auto_assign_billing_account=true \
  "$PROJECT_ID_BASE" > "$TMP_OUTPUT" 2>&1
EXIT_CODE=$?
set -e

PROJECT_ID=$(grep -iE "project[_ ]id:" "$TMP_OUTPUT" | head -n 1 | awk -F':' '{print $2}' | tr -d ' "' || true)

# If a project ID was found, verify if it is active and accessible via gcloud
if [ -n "$PROJECT_ID" ]; then
  echo "Verifying project accessibility..."
  if gcloud projects describe "$PROJECT_ID" >/dev/null 2>&1; then
    EXIT_CODE=0
  else
    echo "⚠️  Project ID '$PROJECT_ID' was found in logs but is not accessible."
    PROJECT_ID=""
  fi
fi

if [ -z "$PROJECT_ID" ]; then
  echo "❌ Error: Failed to create GCP Playground project."
  echo "-----------------------------------------------------------------"
  echo "Raw Command Output:"
  cat "$TMP_OUTPUT"
  echo "-----------------------------------------------------------------"
  
  # Check for known failure modes
  if grep -qi "terms of service\|go/experimental-gcp-project-creation" "$TMP_OUTPUT"; then
    echo "⚠️  POLICY BLOCKER DETECTED:"
    echo "   You must accept the Experimental GCP Project Creation Terms of Service."
    echo "   Please visit this link in your browser, accept the terms, and try again:"
    echo "   👉 http://go/experimental-gcp-project-creation"
  elif grep -qi "too long\|30 characters" "$TMP_OUTPUT"; then
    echo "⚠️  CONSTRAINT VIOLATION:"
    echo "   The generated project ID base was too long."
    echo "   GCP project IDs must be 30 characters or less."
  fi
  echo "================================================================="
  exit 1
fi

echo "✅ Project created successfully: $PROJECT_ID"
echo "Setting active gcloud project..."
gcloud config set project "$PROJECT_ID"

# --- 2. Initialize Terraform & Provision Resources ---
echo ""
echo "Step 2: Initializing and running Terraform..."
IMAGE_URL="${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY_NAME}/${IMAGE_NAME}:latest"

terraform init

echo "Provisioning resources (APIs, GCS bucket, Registry, IAM bindings)..."
terraform apply -auto-approve \
  -var="project_id=${PROJECT_ID}" \
  -var="region=${REGION}" \
  -var="repository_name=${REPOSITORY_NAME}" \
  -var="service_name=${SERVICE_NAME}" \
  -var="image_url=${IMAGE_URL}" \
  -var="container_port=${CONTAINER_PORT}" \
  -var="cpu=${CPU}" \
  -var="memory=${MEMORY}" \
  -var="corp_email=${CORP_EMAIL}" \
  -var="personal_email=${PERSONAL_EMAIL}"

# Fetch the generated bucket name from outputs
GCS_BUCKET_NAME=$(terraform output -raw gcs_bucket_name)
echo "✅ Infrastructure provisioned."
echo "   Created persistent GCS storage bucket: gs://${GCS_BUCKET_NAME}"

# --- 3. Build and Push Docker Image ---
echo ""
echo "Step 3: Building and pushing Docker container..."
echo "Configuring docker authentication for Artifact Registry..."
gcloud auth configure-docker "${REGION}-docker.pkg.dev" --quiet

# Build utilizing the repository root context (..) and root Dockerfile (../Dockerfile)
echo "Compiling optimized Go binary inside multi-stage Docker build..."
docker build -t "${IMAGE_URL}" -f "../Dockerfile" ..

echo "Pushing container image to Artifact Registry..."
docker push "${IMAGE_URL}"
echo "✅ Container successfully uploaded to Artifact Registry."

# --- 4. Deploy and Update Cloud Run Service ---
echo ""
echo "Step 4: Updating Cloud Run service with the new image..."
gcloud run deploy "${SERVICE_NAME}" \
    --image="${IMAGE_URL}" \
    --region="${REGION}" \
    --port="${CONTAINER_PORT}" \
    --cpu="${CPU}" \
    --memory="${MEMORY}" \
    --project="${PROJECT_ID}" \
    --no-allow-unauthenticated

# --- 5. Output Environment Metadata File ---
echo "Step 5: Outputting env_metadata.sh metadata file..."
cat << EOF > env_metadata.sh
# Generated by setup_playground.sh on $(date)
export PROJECT_ID="${PROJECT_ID}"
export REGION="${REGION}"
export REPOSITORY_NAME="${REPOSITORY_NAME}"
export IMAGE_NAME="${IMAGE_NAME}"
export SERVICE_NAME="${SERVICE_NAME}"
export CONTAINER_PORT="${CONTAINER_PORT}"
export CPU="${CPU}"
export MEMORY="${MEMORY}"
export CORP_EMAIL="${CORP_EMAIL}"
export PERSONAL_EMAIL="${PERSONAL_EMAIL}"
export GCS_BUCKET_NAME="${GCS_BUCKET_NAME}"
EOF
chmod +x env_metadata.sh
echo "✅ Shared environment metadata file created: env_metadata.sh"

# --- 6. Manual IAP & OAuth Configuration Summary ---
CLOUD_RUN_URL=$(terraform output -raw cloud_run_url)
echo ""
echo "================================================================="
echo "🎉 GCP Playground deployment bootstrapper finished successfully!"
echo "================================================================="
echo "Project ID:            ${PROJECT_ID}"
echo "Persistent GCS Bucket: gs://${GCS_BUCKET_NAME}"
echo "Cloud Run HTTPS URL:   ${CLOUD_RUN_URL}"
echo "================================================================="
echo ""
echo "👉 ACTION REQUIRED: Securely access your dashboard via proxy:"
echo "Your database is secured using native Cloud IAM and is NOT publicly accessible."
echo "To safely view the dashboard in your browser, spin up a secure local proxy:"
echo ""
echo "   gcloud run services proxy ${SERVICE_NAME} --project=${PROJECT_ID} --region=${REGION} --port=8080"
echo ""
echo "Then, open http://localhost:8080 in your web browser!"
echo "================================================================="
